name: reference_harmony
description: A cross-platform reference cheat sheet app for HarmonyOS built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  path_provider: ^2.1.1
  intl: ^0.20.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/reference/zh/
    - assets/reference/en/
    - assets/fonts/

  fonts:
    - family: FontAwesomeSolid
      fonts:
        - asset: assets/fonts/fa-solid-900.ttf
